/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolbillingsystem;

//import dbtest.sqliteConnection;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.print.PrinterException;
import java.io.FileOutputStream;
import static java.lang.String.valueOf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author roshank
 */
public class getTCN1 extends javax.swing.JFrame {
    
    
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;

    /**
     * Creates new form feePayRec
     */
    public getTCN1() {
        initComponents();
        conn=sqliteConnection.ConnectDB();
        CurrentDate();
    }
    
    
    public void CurrentDate(){
        Calendar cal= new GregorianCalendar();
        int month= cal.get(Calendar.MONTH);
        int year= cal.get(Calendar.YEAR);
        int day= cal.get(Calendar.DAY_OF_MONTH);
        txt_date.setText("Current Date-"+year+"/"+(month+1)+"/"+day);
        
        
        int second= cal.get(Calendar.SECOND);
        int minute= cal.get(Calendar.MINUTE);
        int hour= cal.get(Calendar.HOUR);
        txt_time.setText("Current Time-"+hour+":"+minute+":"+second);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        getBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        pgname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ad = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        getTCBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        dob = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cls = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        doa = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        prcls = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lstdate = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        rslt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        con = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tcno = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        txt_date = new javax.swing.JMenu();
        txt_time = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolbillingsystem/images/Places-certificate-server-icon.png"))); // NOI18N
        jLabel1.setText("Transfer Certificate");

        jLabel2.setText("Enter UID:");

        jLabel3.setText("Name:");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        getBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolbillingsystem/images/loadicon.png"))); // NOI18N
        getBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Name of Parent/Gurdian:");

        jLabel11.setText("Admission No:");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolbillingsystem/images/Apps-Dialog-Logout-icon (1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        getTCBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolbillingsystem/images/certificate-icon.png"))); // NOI18N
        getTCBtn.setText("Generate T.C");
        getTCBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getTCBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Date of Birth:");

        jLabel5.setText("Admitted Class Name:");

        jLabel6.setText("Date of Admission:");

        jLabel7.setText("Present Class:");

        jLabel8.setText("Last Date of Attendence:");

        jLabel10.setText("Result at end Aca Year:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolbillingsystem/images/addicon.png"))); // NOI18N
        jButton1.setText("Submit");

        jLabel12.setText("Conduct:");

        con.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conActionPerformed(evt);
            }
        });

        jLabel13.setText("TC No:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolbillingsystem/images/h1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolbillingsystem/images/Certificate-icon (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(name)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(uid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addComponent(pgname)
                    .addComponent(ad)
                    .addComponent(dob)
                    .addComponent(cls)
                    .addComponent(doa)
                    .addComponent(con)
                    .addComponent(rslt)
                    .addComponent(lstdate, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(prcls)
                    .addComponent(tcno))
                .addGap(208, 208, 208)
                .addComponent(jLabel14)
                .addGap(159, 159, 159))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(360, 360, 360)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 386, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(58, 58, 58))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jButton1)
                        .addGap(46, 46, 46)
                        .addComponent(getTCBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(4, 4, 4))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(getBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(uid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(pgname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(doa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel14))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tcno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(prcls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(cls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lstdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(rslt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(con, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(getTCBtn))
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        txt_date.setText("Date");
        jMenuBar1.add(txt_date);

        txt_time.setText("Time");
        jMenuBar1.add(txt_time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        private JFrame frame;
    private void getBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getBtnActionPerformed
        
        try{
       String sql="SELECT NAME,CLASS, adm_no, DATE_OF_BIRTH, CLASS, DATE_OF_ADM, FATHER, TCNO FROM StuDetail where UID=?";
       pst=conn.prepareStatement(sql);
       pst.setString(1, uid.getText() );
       
       rs=pst.executeQuery();
       while(rs.next()){
           ad.setText(rs.getString("adm_no"));
           name.setText(rs.getString("NAME"));
           pgname.setText(rs.getString("FATHER"));
           dob.setText(rs.getString("DATE_OF_BIRTH"));
           cls.setText(rs.getString("CLASS"));
           doa.setText(rs.getString("DATE_OF_ADM"));
           tcno.setText(rs.getString("TCNO"));
           
           
       }
        
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
            
        }
        
        finally{
            try{
                rs.close();
                pst.close();
                
            }catch(Exception e){
                 JOptionPane.showMessageDialog(null, e);
                
            }
        }
        
    }//GEN-LAST:event_getBtnActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        welcomeUser wu=new welcomeUser();
	wu.setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(null, "Welcome Back User ");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void getTCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getTCBtnActionPerformed
        
        
        
        
                
        
        try{
            /*String sql="SELECT  adm_no,, NAME, FNAME, MNAME, RELIGION, CATEGORY, DATE_OF_BIRTH, DATE_OF_ADM, IDEN1 FROM StuDetail where UID=?";
        pst=conn.prepareStatement(sql);
        pst.setString(1, uid.getText());
        rs = pst.executeQuery();
       
       rs=pst.executeQuery();
       if(rs.next()){
        v1 = rs.getString("adm_no");
        v2 = rs.getString("NAME");
        v3 = rs.getString("FNAME");
        v4 = rs.getString("MNAME");
        v5 = rs.getString("RELOGION");
        v6 = rs.getString("CATEGORY");
        v7 = rs.getString("DATE_OF_BIRTH");
        v8 = rs.getString("DATE_OF_ADM");
        v9 = rs.getString("IDENM1");
       /* v10 = rs.getString("DATE");
        v11 = rs.getString("DATE");
        v12 = rs.getString("DATE");
        v13 = rs.getString("DATE");
        v14 = rs.getString("DATE");
        v15 = rs.getString("DATE");
        v16 = rs.getString("DATE");
        v17 = rs.getString("DATE");
        v18 = rs.getString("DATE");
        rs.close();
        pst.close(); */
        
       
        
        
        
        
        Document doc =new Document();
        PdfWriter.getInstance(doc, new FileOutputStream("tc.pdf"));
        doc.open();
        Image image = Image.getInstance("logo.png");
        //image.setAlignment(Element.ALIGN_CENTER);
        doc.add(image); 
        
     /*   Paragraph pic = new Paragraph(new Date().toString());
        pic.setAlignment(Element.ALIGN_RIGHT);
        doc.add(pic);
        
        Paragraph p1 = new Paragraph("LOYOLA HIGH SCHOOL",FontFactory.getFont(FontFactory.TIMES_BOLD,24,Font.BOLD,BaseColor.BLUE));
        p1.setAlignment(Element.ALIGN_CENTER);
        doc.add(p1);
        
        Paragraph p2 = new Paragraph("ENGLISH MEDIUM",FontFactory.getFont(FontFactory.TIMES_BOLD,16));
        p2.setAlignment(Element.ALIGN_CENTER);
        doc.add(p2);
        
        Paragraph p3 = new Paragraph("(Govt. Recog. No. 3257/A4/2013)",FontFactory.getFont(FontFactory.TIMES_BOLD,16));
        p3.setAlignment(Element.ALIGN_CENTER);
        doc.add(p3);
        
        Paragraph p4 = new Paragraph("",FontFactory.getFont(FontFactory.TIMES_BOLD,16));
        p4.setAlignment(Element.ALIGN_CENTER);
        doc.add(p4);*/
        
        //Chunk reportTitle= new Chunk("Candidate Login Report \t\t\t\t\t\t\t\t\t\t ");
      
        
            //Paragraph paragraph = new Paragraph(10);
            //paragraph.add(new Chunk("Loyola High Schhol"));
            //paragraph.add(new Chunk("11-09-2015"));
            //paragraph.add(new Chunk("\nOrder Id:"));
            //paragraph.add(new Chunk("OrderId#12345"));
            //paragraph.setAlignment(Element.ALIGN_CENTER);
            //doc.add(paragraph);

        //Phrase phrase = new Phrase();
        //phrase.add(reportTitle);

        //Paragraph para = new Paragraph();
        //para.add(phrase);
       // doc.add(para);

        
        
        //doc.add(new Paragraph("LOYOLA HIGH SCHOOL",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD,BaseColor.BLUE)));
       // doc.add(new Paragraph("ENGLISH MEDIUM"));
       // doc.add(new Paragraph("(Govt. Recog. No. 3257/A4/2013)"));
       // doc.add(new Paragraph("Loyola Nagar, Jangao Road, SURYAPET-508213"));
        
       // doc.setHorizontalAlignment(Element.ALIGN_RIGHT);
        doc.add(new Paragraph("----------------------------------------------------------------------------------------------------------------------------------"));
        Paragraph ptitle = new Paragraph("TRANSFER CERTIFICATE",FontFactory.getFont(FontFactory.TIMES_BOLD,16));
        ptitle.setAlignment(Element.ALIGN_CENTER);
        doc.add(ptitle);
        
        String tuid=uid.getText();
        String tcNo=tcno.getText();
        String admNo=ad.getText();
        String tname=name.getText();
        String tpname=pgname.getText();
        String tdob=dob.getText();
        String tcls=cls.getText();
        String tdoa=doa.getText();
        String tpcls=prcls.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String tdate = sdf.format(lstdate.getDate());
        String trslt=rslt.getText();
        String tcon=con.getText();
            Paragraph ptcNo = new Paragraph(10);
            ptcNo.add(new Chunk("\nTC No: "+tcNo,FontFactory.getFont(FontFactory.COURIER,15)));
            ptcNo.add(new Chunk("\u00a0 \u00a0 \u00a0\u00a0 \u00a0 \u00a0\u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0 Admission No: "+admNo,FontFactory.getFont(FontFactory.COURIER,15)));
            doc.add(ptcNo);
            
            
            Paragraph puid = new Paragraph(10);
            puid.add(new Chunk("\n\n\n1. U.I.D of the Student \u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0:\u00a0\u00a0"+tuid,FontFactory.getFont(FontFactory.TIMES,15)));;
            puid.setAlignment(Element.ALIGN_LEFT);
            doc.add(puid);
            
            
        
            Paragraph p1 = new Paragraph(10);
            p1.add(new Chunk("\n\n\n2. Name of the Student \u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0:\u00a0\u00a0"+tname,FontFactory.getFont(FontFactory.TIMES,15)));;
            p1.setAlignment(Element.ALIGN_LEFT);
            doc.add(p1);
            
            Paragraph p2 = new Paragraph(10);
            p2.add(new Chunk("\n\n\n3. Name of the Parent/Guardian \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0:\u00a0\u00a0"+tpname,FontFactory.getFont(FontFactory.TIMES,15)));
            p2.setAlignment(Element.ALIGN_LEFT);
            doc.add(p2);
            
            Paragraph p3 = new Paragraph(10);
            p3.add(new Chunk("\n\n\n4. Date of Birth \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0:\u00a0\u00a0"+tdob,FontFactory.getFont(FontFactory.TIMES,15)));
            p3.setAlignment(Element.ALIGN_LEFT);
            doc.add(p3);
            
            Paragraph p4 = new Paragraph(10);
            p4.add(new Chunk("\n\n\n5. Class to which He/She was admitted \u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0:\u00a0\u00a0"+tcls,FontFactory.getFont(FontFactory.TIMES,15)));
            p4.setAlignment(Element.ALIGN_LEFT);
            doc.add(p4);
            
            Paragraph p5= new Paragraph(10);
            p5.add(new Chunk("\n\n\n6. Date of Admission \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0:\u00a0\u00a0"+tdoa,FontFactory.getFont(FontFactory.TIMES,15)));
            p5.setAlignment(Element.ALIGN_LEFT);
            doc.add(p5);
            
            Paragraph p6 = new Paragraph(10);
            p6.add(new Chunk("\n\n\n7. The present Class \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0:\u00a0\u00a0"+tpcls,FontFactory.getFont(FontFactory.TIMES,15)));
            p6.setAlignment(Element.ALIGN_LEFT);
            doc.add(p6);
            
            Paragraph p7 = new Paragraph(10);
            p7.add(new Chunk("\n\n\n8. Last date of attendece in the school \u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0:\u00a0\u00a0"+tdate,FontFactory.getFont(FontFactory.TIMES,15)));
            p7.setAlignment(Element.ALIGN_LEFT);
            doc.add(p7);
            
            Paragraph p8 = new Paragraph(10);
            p8.add(new Chunk("\n\n\n9. Result at end of the academinc year \u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0:\u00a0\u00a0"+trslt,FontFactory.getFont(FontFactory.TIMES,15)));
            p8.setAlignment(Element.ALIGN_LEFT);
            doc.add(p8);
            
            Paragraph p9 = new Paragraph(10);
            p9.add(new Chunk("\n\n\n10. Conduct \u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                     + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                     + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                     + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                     + "\u00a0\u00a0\u00a0\u00a0\u00a0"
                    + "\u00a0\u00a0\u00a0\u00a0\u00a0:\u00a0\u00a0"+tcon,FontFactory.getFont(FontFactory.TIMES,15)));
            p9.setAlignment(Element.ALIGN_LEFT);
            doc.add(p9);
            
            
            Paragraph p10 = new Paragraph(10);
            p10.add(new Chunk("\n\n\n\n\n\n\n\nSIGNATURE OF PRINCIPAL \u00a0\u00a0\u00a0\u00a0\u00a0 \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0 \u00a0\u00a0 STAMP \n\n\n\n\n\n\n\n",FontFactory.getFont(FontFactory.COURIER,15)));
            p10.setAlignment(Element.ALIGN_LEFT);
            doc.add(p10);
            
            
            
            doc.add(new Paragraph(new Date().toString()));
  
            
        
        doc.close();
                 JOptionPane.showMessageDialog(null, "T.C. Generated");
        
        
        
        
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, "Eception");
               
               }
        
       /* try{
            
        

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }*/
        
        
        
      /*  getTc.append(
                
                
                "\t\t\t LOYOLA HIGH SCHOOL"
                        + "\n\t\t\t ENGLISH MEDIUM"
                        + "\n \t\t\t (Govt. Recog. No. 3257/A4/2013)"
                        + "\n \t\t\t Loyola Nagar, Jangao Road, SURYAPET-508213" +
                "\n------------------------------------------------------------------------------------------------------\n"
                        + "\t\t\tTRANSFER CERTIFICATE\n " +
                "Payee Admission No : \t\t" +ad.getText() + "\n\n\n"+
                "Payee UID : \t\t" +uid.getText() + "\n\n\n"+
                //"Payee Name:           \t\t"+name.getText()+ "\n\n\n"+
                //"Payee Class:          \t\t"+cls.getText()+"\n\n\n"+
                //"Total Fee:            \t\t"+tfee.getText()+"\n\n\n"+
                //"concession:      \t\t"+conce.getText()+"\n\n\n"+
                //"Paid Fee:             \t\t"+pfee.getText()+"\n\n\n"+
                //"Date of Payment:      \t\t"+dop+"\n\n\n"+
                //"Purpose:              \t\t"+purp.getText()+"\n\n\n"+
                //"Due Amount:           \t\t"+z+"\n\n\n"+
                //"\t\t \t\t \t \tAuthorized signature\n\n\n"+
                
                "For office use" +
                "\n--------------------------------------------------------------------------------------------------\n" +
                "Payee Admission No : \t\t" +ad.getText() + "\n\n\n"
               // "Payee UID : \t\t" +uid.getText() + "\n\n\n"+
               // "Payee Name:           \t\t"+name.getText()+ "\n\n\n"+
                //"Payee Class:          \t\t"+cls.getText()+"\n\n\n"+
                //"Total Fee:            \t\t"+tfee.getText()+"\n\n\n"+
                //"concession:      \t\t"+conce.getText()+"\n\n\n"+
                //"Paid Fee:             \t\t"+pfee.getText()+"\n\n\n"+
                //"Date of Payment:      \t\t"+dop+"\n\n\n"+
                //"Purpose:              \t\t"+purp.getText()+"\n\n\n"+
                //"Due Amount:           \t\t"+z+"\n\n\n"+
                //"\t\t \t\t \t \tAuthorized signature\n\n\n"
                
                
                
               
     
                 );*/
        
        
        
    }//GEN-LAST:event_getTCBtnActionPerformed

    private void conActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         SchoolBillingSystem sbs=new SchoolBillingSystem();
        sbs.setVisible(true);
        dispose();
        JOptionPane.showMessageDialog(null, "Welcome Back to Home");

    }//GEN-LAST:event_jButton2ActionPerformed

    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getTCN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(getTCN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(getTCN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(getTCN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new getTCN1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad;
    private javax.swing.JTextField cls;
    private javax.swing.JTextField con;
    private javax.swing.JTextField doa;
    private javax.swing.JTextField dob;
    private javax.swing.JButton getBtn;
    private javax.swing.JButton getTCBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser lstdate;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pgname;
    private javax.swing.JTextField prcls;
    private javax.swing.JTextField rslt;
    private javax.swing.JTextField tcno;
    private javax.swing.JMenu txt_date;
    private javax.swing.JMenu txt_time;
    private javax.swing.JTextField uid;
    // End of variables declaration//GEN-END:variables
}
